### PR TITLE
Bookstore: create and remove books

### PR DESCRIPTION
**Pull request by DammyShittu**
## In this PR, I;
- configured the Redux Store and imported the necessary methods from Redux,
- added a `reducer` to change app state after an action has been received,
- Implement methods to add and remove books by dispatching corresponding actions, and
- correctly set up linters.

### CODE REVIEW

**Review by GzimAsani — APPROVED** [review]
# Hello @DammyShittu      

## Thank you for implementing all the project requirements, yo've done a great job :trophy:  . Your project is **ACCEPTED :green_circle:** and I wish you the best of luck in your next projects :+1: 

 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
 You can also consider:
 
- [  **_Optional_** ] Your delete button is not being appended to the page. Kindly add that.

 Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by DammyShittu** [comment]
Hi @GzimAsani,
Thank you for reviewing my project. 
I currently do not fully  understand what you mean by the "delete button not being appended to the page".
Kindly expatiate.

Cheers 🎉

**Comment by GzimAsani** [comment]
> Hi @GzimAsani, Thank you for reviewing my project. I currently do not fully understand what you mean by the "delete button not being appended to the page". Kindly expatiate.
> 
> Cheers tada

There should be a button similar to thisScreenshot from 2021-09-29 00-10-33 which when clicked would remove the book

**Comment by DammyShittu** [comment]
> > Hi @GzimAsani, Thank you for reviewing my project. I currently do not fully understand what you mean by the "delete button not being appended to the page". Kindly expatiate.
> > Cheers tada
> 
> There should be a button similar to thisScreenshot from 2021-09-29 00-10-33 which when clicked would remove the book

Thank you for the reply @GzimAsani 
I'll look into it.

**Pull request merged**
